// Generated by CoffeeScript 1.8.0
var shell;

shell = require('shelljs');

shell.config.fatal = true;

require('shelljs/global');

ln('-s', '/usr/bin/nodejs', '/usr/bin/node');

rm('-rf', '/etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh');

cp('consul', '/usr/local/bin/consul');

mkdir('/etc/service/consul');

cp('consul.sh', '/etc/service/consul/run');

mkdir('/etc/service/consul/control');

cp('consul-down.sh', '/etc/service/consul/control/t');

'2'.to('/etc/container_environment/GOMAXPROCS');

mkdir('/consul-data');

exec('npm install -g consul-doppelganger');

mkdir('/etc/service/doppelganger');

cp('doppelganger.sh', '/etc/service/doppelganger/run');

exec('npm install -g redwire-harmony');

mkdir('/etc/service/harmony');

cp('harmony.sh', '/etc/service/harmony/run');

mkdir('/consul');

mkdir('/doppelganger');

mkdir('/harmony');
