// Generated by CoffeeScript 1.8.0
module.exports = {
  config: {
    http: {
      port: 8888
    }
  },
  bind: function(redwire, bindings) {
    return bindings.http('http://localhost:8888/').use(function(mount, url, req, res, next) {
      res.write('OK');
      return res.end();
    });
  }
};
