// Generated by CoffeeScript 1.8.0
var fs;

fs = require('fs');

module.exports = function(dir, current, callback) {
  var a, d, e, item, items, k, m, path, pool, stat, u, v, _i, _len;
  a = {};
  d = {};
  m = {};
  u = {};
  pool = {};
  for (k in current) {
    v = current[k];
    pool[k] = v;
  }
  try {
    items = fs.readdirSync(dir);
  } catch (_error) {
    e = _error;
    console.error("Could not open directory " + dir);
    return callback(a, d, m, pool);
  }
  for (_i = 0, _len = items.length; _i < _len; _i++) {
    item = items[_i];
    if (!item.match(/\.js$/)) {
      continue;
    }
    path = "" + dir + "/" + item;
    stat = fs.statSync(path);
    if (pool[item] != null) {
      if (pool[item].changed < stat.mtime.getTime()) {
        m[item] = {
          path: path,
          changed: stat.mtime.getTime()
        };
      } else {
        u[item] = {
          path: path,
          changed: stat.mtime.getTime()
        };
      }
      delete pool[item];
    } else {
      a[item] = {
        path: path,
        changed: stat.mtime.getTime()
      };
    }
  }
  for (k in pool) {
    v = pool[k];
    d[k] = v;
  }
  return callback(a, d, m, u);
};
